# Simple Linear Regression

Used for data with one feature, one dependent value.


## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

## Importing the dataset

In [4]:
dataset = pd.read_csv('Salary_Data.csv')
x = dataset.iloc[:,:1].values
y = dataset.iloc[:,1:].values

print(x)

print(y)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
[[ 39343.]
 [ 46205.]
 [ 37731.]
 [ 43525.]
 [ 39891.]
 [ 56642.]
 [ 60150.]
 [ 54445.]
 [ 64445.]
 [ 57189.]
 [ 63218.]
 [ 55794.]
 [ 56957.]
 [ 57081.]
 [ 61111.]
 [ 67938.]
 [ 66029.]
 [ 83088.]
 [ 81363.]
 [ 93940.]
 [ 91738.]
 [ 98273.]
 [101302.]
 [113812.]
 [109431.]
 [105582.]
 [116969.]
 [112635.]
 [122391.]
 [121872.]]


## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[ 9.6]
 [ 4. ]
 [ 5.3]
 [ 7.9]
 [ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]
[[ 1.5]
 [10.3]
 [ 4.1]
 [ 3.9]
 [ 9.5]
 [ 8.7]]
[[112635.]
 [ 55794.]
 [ 83088.]
 [101302.]
 [ 56642.]
 [ 66029.]
 [ 64445.]
 [ 61111.]
 [113812.]
 [ 91738.]
 [ 46205.]
 [121872.]
 [ 60150.]
 [ 39891.]
 [ 81363.]
 [ 93940.]
 [ 57189.]
 [ 54445.]
 [105582.]
 [ 43525.]
 [ 39343.]
 [ 98273.]
 [ 67938.]
 [ 56957.]]
[[ 37731.]
 [122391.]
 [ 57081.]
 [ 63218.]
 [116969.]
 [109431.]]


## Training the Simple Linear Regression model on the Training set

Fit method - training the model.

In [12]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

## Predicting the Test set results

In [21]:
predicted = regressor.predict(x_test)
print(predicted)

[[ 40748.96184072]
 [122699.62295594]
 [ 64961.65717022]
 [ 63099.14214487]
 [115249.56285456]
 [107799.50275317]]


## Visualising the Training set results

## Visualising the Test set results